#include <ppc/ppc_context.h>

// AUTO-GENERATED by tools (see docs/ARCHITECTURE.md).
// Taking the address of every import forces the linker to resolve it.
// Generated CRT register-save/restore bodies use PPC_FUNC_IMPL (C linkage),
// whereas host import wrappers use PPC_FUNC (C++ linkage).
// Use the generator's PPCFunc, including its restricted reference parameter.
// Omitting __restrict changes C++ symbol decoration on Windows/ClangCL.

extern PPCFunc __imp__DbgBreakPoint;
extern PPCFunc __imp__DbgPrint;
extern PPCFunc __imp__ExAllocatePoolTypeWithTag;
extern PPCFunc __imp__ExCreateThread;
extern PPCFunc __imp__ExFreePool;
extern PPCFunc __imp__ExGetXConfigSetting;
extern PPCFunc __imp__ExRegisterTitleTerminateNotification;
extern PPCFunc __imp__ExTerminateThread;
extern PPCFunc __imp__FscSetCacheElementCount;
extern PPCFunc __imp__HalReturnToFirmware;
extern PPCFunc __imp__InterlockedFlushSList;
extern PPCFunc __imp__InterlockedPopEntrySList;
extern PPCFunc __imp__IoCheckShareAccess;
extern PPCFunc __imp__IoCompleteRequest;
extern PPCFunc __imp__IoCreateDevice;
extern PPCFunc __imp__IoDeleteDevice;
extern PPCFunc __imp__IoInvalidDeviceRequest;
extern PPCFunc __imp__IoRemoveShareAccess;
extern PPCFunc __imp__IoSetShareAccess;
extern PPCFunc __imp__KeAcquireSpinLockAtRaisedIrql;
extern PPCFunc __imp__KeBugCheck;
extern PPCFunc __imp__KeBugCheckEx;
extern PPCFunc __imp__KeDelayExecutionThread;
extern PPCFunc __imp__KeEnterCriticalRegion;
extern PPCFunc __imp__KeGetCurrentProcessType;
extern PPCFunc __imp__KeInitializeDpc;
extern PPCFunc __imp__KeInsertQueueDpc;
extern PPCFunc __imp__KeLeaveCriticalRegion;
extern PPCFunc __imp__KeLockL2;
extern PPCFunc __imp__KeQueryBasePriorityThread;
extern PPCFunc __imp__KeQueryPerformanceFrequency;
extern PPCFunc __imp__KeQuerySystemTime;
extern PPCFunc __imp__KeReleaseSpinLockFromRaisedIrql;
extern PPCFunc __imp__KeResetEvent;
extern PPCFunc __imp__KeSetAffinityThread;
extern PPCFunc __imp__KeSetBasePriorityThread;
extern PPCFunc __imp__KeSetCurrentProcessType;
extern PPCFunc __imp__KeSetEvent;
extern PPCFunc __imp__KeTlsAlloc;
extern PPCFunc __imp__KeTlsFree;
extern PPCFunc __imp__KeTlsGetValue;
extern PPCFunc __imp__KeTlsSetValue;
extern PPCFunc __imp__KeUnlockL2;
extern PPCFunc __imp__KeWaitForMultipleObjects;
extern PPCFunc __imp__KeWaitForSingleObject;
extern PPCFunc __imp__KfAcquireSpinLock;
extern PPCFunc __imp__KfReleaseSpinLock;
extern PPCFunc __imp__KiApcNormalRoutineNop;
extern PPCFunc __imp__MmAllocatePhysicalMemoryEx;
extern PPCFunc __imp__MmFreePhysicalMemory;
extern PPCFunc __imp__MmGetPhysicalAddress;
extern PPCFunc __imp__MmMapIoSpace;
extern PPCFunc __imp__MmQueryAddressProtect;
extern PPCFunc __imp__MmQueryAllocationSize;
extern PPCFunc __imp__NetDll_WSACleanup;
extern PPCFunc __imp__NetDll_WSAStartup;
extern PPCFunc __imp__NetDll_XNetGetTitleXnAddr;
extern PPCFunc __imp__NetDll_XNetStartup;
extern PPCFunc __imp__NetDll___WSAFDIsSet;
extern PPCFunc __imp__NetDll_accept;
extern PPCFunc __imp__NetDll_bind;
extern PPCFunc __imp__NetDll_closesocket;
extern PPCFunc __imp__NetDll_connect;
extern PPCFunc __imp__NetDll_inet_addr;
extern PPCFunc __imp__NetDll_listen;
extern PPCFunc __imp__NetDll_recv;
extern PPCFunc __imp__NetDll_select;
extern PPCFunc __imp__NetDll_send;
extern PPCFunc __imp__NetDll_setsockopt;
extern PPCFunc __imp__NetDll_socket;
extern PPCFunc __imp__NtAllocateVirtualMemory;
extern PPCFunc __imp__NtClearEvent;
extern PPCFunc __imp__NtClose;
extern PPCFunc __imp__NtCreateEvent;
extern PPCFunc __imp__NtCreateFile;
extern PPCFunc __imp__NtCreateSemaphore;
extern PPCFunc __imp__NtDuplicateObject;
extern PPCFunc __imp__NtFlushBuffersFile;
extern PPCFunc __imp__NtFreeVirtualMemory;
extern PPCFunc __imp__NtOpenFile;
extern PPCFunc __imp__NtQueryDirectoryFile;
extern PPCFunc __imp__NtQueryFullAttributesFile;
extern PPCFunc __imp__NtQueryInformationFile;
extern PPCFunc __imp__NtQueryVirtualMemory;
extern PPCFunc __imp__NtQueryVolumeInformationFile;
extern PPCFunc __imp__NtReadFile;
extern PPCFunc __imp__NtReadFileScatter;
extern PPCFunc __imp__NtReleaseSemaphore;
extern PPCFunc __imp__NtResumeThread;
extern PPCFunc __imp__NtSetEvent;
extern PPCFunc __imp__NtSetInformationFile;
extern PPCFunc __imp__NtSuspendThread;
extern PPCFunc __imp__NtWaitForSingleObjectEx;
extern PPCFunc __imp__NtWriteFile;
extern PPCFunc __imp__NtWriteFileGather;
extern PPCFunc __imp__ObCreateSymbolicLink;
extern PPCFunc __imp__ObDeleteSymbolicLink;
extern PPCFunc __imp__ObDereferenceObject;
extern PPCFunc __imp__ObIsTitleObject;
extern PPCFunc __imp__ObReferenceObject;
extern PPCFunc __imp__ObReferenceObjectByHandle;
extern PPCFunc __imp__RtlCaptureContext;
extern PPCFunc __imp__RtlCompareMemoryUlong;
extern PPCFunc __imp__RtlCompareStringN;
extern PPCFunc __imp__RtlEnterCriticalSection;
extern PPCFunc __imp__RtlFillMemoryUlong;
extern PPCFunc __imp__RtlFreeAnsiString;
extern PPCFunc __imp__RtlImageXexHeaderField;
extern PPCFunc __imp__RtlInitAnsiString;
extern PPCFunc __imp__RtlInitUnicodeString;
extern PPCFunc __imp__RtlInitializeCriticalSection;
extern PPCFunc __imp__RtlInitializeCriticalSectionAndSpinCount;
extern PPCFunc __imp__RtlLeaveCriticalSection;
extern PPCFunc __imp__RtlMultiByteToUnicodeN;
extern PPCFunc __imp__RtlNtStatusToDosError;
extern PPCFunc __imp__RtlRaiseException;
extern PPCFunc __imp__RtlTimeFieldsToTime;
extern PPCFunc __imp__RtlTimeToTimeFields;
extern PPCFunc __imp__RtlTryEnterCriticalSection;
extern PPCFunc __imp__RtlUnicodeStringToAnsiString;
extern PPCFunc __imp__RtlUnicodeToMultiByteN;
extern PPCFunc __imp__RtlUnwind;
extern PPCFunc __imp__RtlUpcaseUnicodeChar;
extern PPCFunc __imp__StfsControlDevice;
extern PPCFunc __imp__StfsCreateDevice;
extern PPCFunc __imp__VdCallGraphicsNotificationRoutines;
extern PPCFunc __imp__VdEnableDisableClockGating;
extern PPCFunc __imp__VdEnableRingBufferRPtrWriteBack;
extern PPCFunc __imp__VdGetCurrentDisplayGamma;
extern PPCFunc __imp__VdGetCurrentDisplayInformation;
extern PPCFunc __imp__VdGetSystemCommandBuffer;
extern PPCFunc __imp__VdInitializeEngines;
extern PPCFunc __imp__VdInitializeRingBuffer;
extern PPCFunc __imp__VdInitializeScalerCommandBuffer;
extern PPCFunc __imp__VdIsHSIOTrainingSucceeded;
extern PPCFunc __imp__VdPersistDisplay;
extern PPCFunc __imp__VdQueryVideoFlags;
extern PPCFunc __imp__VdQueryVideoMode;
extern PPCFunc __imp__VdRetrainEDRAM;
extern PPCFunc __imp__VdRetrainEDRAMWorker;
extern PPCFunc __imp__VdSetDisplayMode;
extern PPCFunc __imp__VdSetDisplayModeOverride;
extern PPCFunc __imp__VdSetGraphicsInterruptCallback;
extern PPCFunc __imp__VdSetSystemCommandBufferGpuIdentifierAddress;
extern PPCFunc __imp__VdShutdownEngines;
extern PPCFunc __imp__VdSwap;
extern PPCFunc __imp__XAudioGetSpeakerConfig;
extern PPCFunc __imp__XAudioGetVoiceCategoryVolume;
extern PPCFunc __imp__XAudioRegisterRenderDriverClient;
extern PPCFunc __imp__XAudioSubmitRenderDriverFrame;
extern PPCFunc __imp__XAudioUnregisterRenderDriverClient;
extern PPCFunc __imp__XGetAVPack;
extern PPCFunc __imp__XGetGameRegion;
extern PPCFunc __imp__XGetLanguage;
extern PPCFunc __imp__XGetVideoCapabilities;
extern PPCFunc __imp__XGetVideoMode;
extern PPCFunc __imp__XMACreateContext;
extern PPCFunc __imp__XMAReleaseContext;
extern PPCFunc __imp__XMsgCancelIORequest;
extern PPCFunc __imp__XMsgInProcessCall;
extern PPCFunc __imp__XMsgStartIORequest;
extern PPCFunc __imp__XMsgStartIORequestEx;
extern PPCFunc __imp__XNotifyGetNext;
extern PPCFunc __imp__XamAlloc;
extern PPCFunc __imp__XamContentClose;
extern PPCFunc __imp__XamContentCreateEnumerator;
extern PPCFunc __imp__XamContentCreateEx;
extern PPCFunc __imp__XamContentDelete;
extern PPCFunc __imp__XamContentGetCreator;
extern PPCFunc __imp__XamContentGetDeviceData;
extern PPCFunc __imp__XamContentGetDeviceState;
extern PPCFunc __imp__XamEnableInactivityProcessing;
extern PPCFunc __imp__XamEnumerate;
extern PPCFunc __imp__XamFree;
extern PPCFunc __imp__XamGetExecutionId;
extern PPCFunc __imp__XamGetSystemVersion;
extern PPCFunc __imp__XamInputGetCapabilities;
extern PPCFunc __imp__XamInputGetState;
extern PPCFunc __imp__XamInputSetState;
extern PPCFunc __imp__XamLoaderLaunchTitle;
extern PPCFunc __imp__XamLoaderTerminateTitle;
extern PPCFunc __imp__XamNotifyCreateListener;
extern PPCFunc __imp__XamParseGamerTileKey;
extern PPCFunc __imp__XamReadTileToTexture;
extern PPCFunc __imp__XamResetInactivity;
extern PPCFunc __imp__XamSessionCreateHandle;
extern PPCFunc __imp__XamSessionRefObjByHandle;
extern PPCFunc __imp__XamShowDeviceSelectorUI;
extern PPCFunc __imp__XamShowDirtyDiscErrorUI;
extern PPCFunc __imp__XamShowGamerCardUIForXUID;
extern PPCFunc __imp__XamShowMessageBoxUI;
extern PPCFunc __imp__XamShowMessageBoxUIEx;
extern PPCFunc __imp__XamShowSigninUI;
extern PPCFunc __imp__XamUserCheckPrivilege;
extern PPCFunc __imp__XamUserCreateStatsEnumerator;
extern PPCFunc __imp__XamUserGetName;
extern PPCFunc __imp__XamUserGetSigninInfo;
extern PPCFunc __imp__XamUserGetSigninState;
extern PPCFunc __imp__XamUserGetXUID;
extern PPCFunc __imp__XamUserReadProfileSettings;
extern PPCFunc __imp__XeCryptBnQwBeSigVerify;
extern PPCFunc __imp__XeCryptRotSumSha;
extern PPCFunc __imp__XeCryptSha;
extern PPCFunc __imp__XeKeysGetKey;
extern PPCFunc __imp__XexCheckExecutablePrivilege;
extern PPCFunc __imp__XexGetModuleHandle;
extern PPCFunc __imp__XexGetModuleSection;
extern PPCFunc __imp__XexGetProcedureAddress;
extern PPCFunc __imp__XexLoadImage;
extern PPCFunc __imp__XexUnloadImage;
extern PPCFunc __imp____C_specific_handler;
extern "C" PPCFunc __imp____restfpr_14;
extern "C" PPCFunc __imp____restfpr_15;
extern "C" PPCFunc __imp____restfpr_16;
extern "C" PPCFunc __imp____restfpr_17;
extern "C" PPCFunc __imp____restfpr_18;
extern "C" PPCFunc __imp____restfpr_19;
extern "C" PPCFunc __imp____restfpr_20;
extern "C" PPCFunc __imp____restfpr_21;
extern "C" PPCFunc __imp____restfpr_22;
extern "C" PPCFunc __imp____restfpr_23;
extern "C" PPCFunc __imp____restfpr_24;
extern "C" PPCFunc __imp____restfpr_25;
extern "C" PPCFunc __imp____restfpr_26;
extern "C" PPCFunc __imp____restfpr_27;
extern "C" PPCFunc __imp____restfpr_28;
extern "C" PPCFunc __imp____restfpr_29;
extern "C" PPCFunc __imp____restfpr_30;
extern "C" PPCFunc __imp____restfpr_31;
extern "C" PPCFunc __imp____restgprlr_14;
extern "C" PPCFunc __imp____restgprlr_15;
extern "C" PPCFunc __imp____restgprlr_16;
extern "C" PPCFunc __imp____restgprlr_17;
extern "C" PPCFunc __imp____restgprlr_18;
extern "C" PPCFunc __imp____restgprlr_19;
extern "C" PPCFunc __imp____restgprlr_20;
extern "C" PPCFunc __imp____restgprlr_21;
extern "C" PPCFunc __imp____restgprlr_22;
extern "C" PPCFunc __imp____restgprlr_23;
extern "C" PPCFunc __imp____restgprlr_24;
extern "C" PPCFunc __imp____restgprlr_25;
extern "C" PPCFunc __imp____restgprlr_26;
extern "C" PPCFunc __imp____restgprlr_27;
extern "C" PPCFunc __imp____restgprlr_28;
extern "C" PPCFunc __imp____restgprlr_29;
extern "C" PPCFunc __imp____restgprlr_30;
extern "C" PPCFunc __imp____restgprlr_31;
extern "C" PPCFunc __imp____restvmx_100;
extern "C" PPCFunc __imp____restvmx_101;
extern "C" PPCFunc __imp____restvmx_102;
extern "C" PPCFunc __imp____restvmx_103;
extern "C" PPCFunc __imp____restvmx_104;
extern "C" PPCFunc __imp____restvmx_105;
extern "C" PPCFunc __imp____restvmx_106;
extern "C" PPCFunc __imp____restvmx_107;
extern "C" PPCFunc __imp____restvmx_108;
extern "C" PPCFunc __imp____restvmx_109;
extern "C" PPCFunc __imp____restvmx_110;
extern "C" PPCFunc __imp____restvmx_111;
extern "C" PPCFunc __imp____restvmx_112;
extern "C" PPCFunc __imp____restvmx_113;
extern "C" PPCFunc __imp____restvmx_114;
extern "C" PPCFunc __imp____restvmx_115;
extern "C" PPCFunc __imp____restvmx_116;
extern "C" PPCFunc __imp____restvmx_117;
extern "C" PPCFunc __imp____restvmx_118;
extern "C" PPCFunc __imp____restvmx_119;
extern "C" PPCFunc __imp____restvmx_120;
extern "C" PPCFunc __imp____restvmx_121;
extern "C" PPCFunc __imp____restvmx_122;
extern "C" PPCFunc __imp____restvmx_123;
extern "C" PPCFunc __imp____restvmx_124;
extern "C" PPCFunc __imp____restvmx_125;
extern "C" PPCFunc __imp____restvmx_126;
extern "C" PPCFunc __imp____restvmx_127;
extern "C" PPCFunc __imp____restvmx_14;
extern "C" PPCFunc __imp____restvmx_15;
extern "C" PPCFunc __imp____restvmx_16;
extern "C" PPCFunc __imp____restvmx_17;
extern "C" PPCFunc __imp____restvmx_18;
extern "C" PPCFunc __imp____restvmx_19;
extern "C" PPCFunc __imp____restvmx_20;
extern "C" PPCFunc __imp____restvmx_21;
extern "C" PPCFunc __imp____restvmx_22;
extern "C" PPCFunc __imp____restvmx_23;
extern "C" PPCFunc __imp____restvmx_24;
extern "C" PPCFunc __imp____restvmx_25;
extern "C" PPCFunc __imp____restvmx_26;
extern "C" PPCFunc __imp____restvmx_27;
extern "C" PPCFunc __imp____restvmx_28;
extern "C" PPCFunc __imp____restvmx_29;
extern "C" PPCFunc __imp____restvmx_30;
extern "C" PPCFunc __imp____restvmx_31;
extern "C" PPCFunc __imp____restvmx_64;
extern "C" PPCFunc __imp____restvmx_65;
extern "C" PPCFunc __imp____restvmx_66;
extern "C" PPCFunc __imp____restvmx_67;
extern "C" PPCFunc __imp____restvmx_68;
extern "C" PPCFunc __imp____restvmx_69;
extern "C" PPCFunc __imp____restvmx_70;
extern "C" PPCFunc __imp____restvmx_71;
extern "C" PPCFunc __imp____restvmx_72;
extern "C" PPCFunc __imp____restvmx_73;
extern "C" PPCFunc __imp____restvmx_74;
extern "C" PPCFunc __imp____restvmx_75;
extern "C" PPCFunc __imp____restvmx_76;
extern "C" PPCFunc __imp____restvmx_77;
extern "C" PPCFunc __imp____restvmx_78;
extern "C" PPCFunc __imp____restvmx_79;
extern "C" PPCFunc __imp____restvmx_80;
extern "C" PPCFunc __imp____restvmx_81;
extern "C" PPCFunc __imp____restvmx_82;
extern "C" PPCFunc __imp____restvmx_83;
extern "C" PPCFunc __imp____restvmx_84;
extern "C" PPCFunc __imp____restvmx_85;
extern "C" PPCFunc __imp____restvmx_86;
extern "C" PPCFunc __imp____restvmx_87;
extern "C" PPCFunc __imp____restvmx_88;
extern "C" PPCFunc __imp____restvmx_89;
extern "C" PPCFunc __imp____restvmx_90;
extern "C" PPCFunc __imp____restvmx_91;
extern "C" PPCFunc __imp____restvmx_92;
extern "C" PPCFunc __imp____restvmx_93;
extern "C" PPCFunc __imp____restvmx_94;
extern "C" PPCFunc __imp____restvmx_95;
extern "C" PPCFunc __imp____restvmx_96;
extern "C" PPCFunc __imp____restvmx_97;
extern "C" PPCFunc __imp____restvmx_98;
extern "C" PPCFunc __imp____restvmx_99;
extern "C" PPCFunc __imp____savefpr_14;
extern "C" PPCFunc __imp____savefpr_15;
extern "C" PPCFunc __imp____savefpr_16;
extern "C" PPCFunc __imp____savefpr_17;
extern "C" PPCFunc __imp____savefpr_18;
extern "C" PPCFunc __imp____savefpr_19;
extern "C" PPCFunc __imp____savefpr_20;
extern "C" PPCFunc __imp____savefpr_21;
extern "C" PPCFunc __imp____savefpr_22;
extern "C" PPCFunc __imp____savefpr_23;
extern "C" PPCFunc __imp____savefpr_24;
extern "C" PPCFunc __imp____savefpr_25;
extern "C" PPCFunc __imp____savefpr_26;
extern "C" PPCFunc __imp____savefpr_27;
extern "C" PPCFunc __imp____savefpr_28;
extern "C" PPCFunc __imp____savefpr_29;
extern "C" PPCFunc __imp____savefpr_30;
extern "C" PPCFunc __imp____savefpr_31;
extern "C" PPCFunc __imp____savegprlr_14;
extern "C" PPCFunc __imp____savegprlr_15;
extern "C" PPCFunc __imp____savegprlr_16;
extern "C" PPCFunc __imp____savegprlr_17;
extern "C" PPCFunc __imp____savegprlr_18;
extern "C" PPCFunc __imp____savegprlr_19;
extern "C" PPCFunc __imp____savegprlr_20;
extern "C" PPCFunc __imp____savegprlr_21;
extern "C" PPCFunc __imp____savegprlr_22;
extern "C" PPCFunc __imp____savegprlr_23;
extern "C" PPCFunc __imp____savegprlr_24;
extern "C" PPCFunc __imp____savegprlr_25;
extern "C" PPCFunc __imp____savegprlr_26;
extern "C" PPCFunc __imp____savegprlr_27;
extern "C" PPCFunc __imp____savegprlr_28;
extern "C" PPCFunc __imp____savegprlr_29;
extern "C" PPCFunc __imp____savegprlr_30;
extern "C" PPCFunc __imp____savegprlr_31;
extern "C" PPCFunc __imp____savevmx_100;
extern "C" PPCFunc __imp____savevmx_101;
extern "C" PPCFunc __imp____savevmx_102;
extern "C" PPCFunc __imp____savevmx_103;
extern "C" PPCFunc __imp____savevmx_104;
extern "C" PPCFunc __imp____savevmx_105;
extern "C" PPCFunc __imp____savevmx_106;
extern "C" PPCFunc __imp____savevmx_107;
extern "C" PPCFunc __imp____savevmx_108;
extern "C" PPCFunc __imp____savevmx_109;
extern "C" PPCFunc __imp____savevmx_110;
extern "C" PPCFunc __imp____savevmx_111;
extern "C" PPCFunc __imp____savevmx_112;
extern "C" PPCFunc __imp____savevmx_113;
extern "C" PPCFunc __imp____savevmx_114;
extern "C" PPCFunc __imp____savevmx_115;
extern "C" PPCFunc __imp____savevmx_116;
extern "C" PPCFunc __imp____savevmx_117;
extern "C" PPCFunc __imp____savevmx_118;
extern "C" PPCFunc __imp____savevmx_119;
extern "C" PPCFunc __imp____savevmx_120;
extern "C" PPCFunc __imp____savevmx_121;
extern "C" PPCFunc __imp____savevmx_122;
extern "C" PPCFunc __imp____savevmx_123;
extern "C" PPCFunc __imp____savevmx_124;
extern "C" PPCFunc __imp____savevmx_125;
extern "C" PPCFunc __imp____savevmx_126;
extern "C" PPCFunc __imp____savevmx_127;
extern "C" PPCFunc __imp____savevmx_14;
extern "C" PPCFunc __imp____savevmx_15;
extern "C" PPCFunc __imp____savevmx_16;
extern "C" PPCFunc __imp____savevmx_17;
extern "C" PPCFunc __imp____savevmx_18;
extern "C" PPCFunc __imp____savevmx_19;
extern "C" PPCFunc __imp____savevmx_20;
extern "C" PPCFunc __imp____savevmx_21;
extern "C" PPCFunc __imp____savevmx_22;
extern "C" PPCFunc __imp____savevmx_23;
extern "C" PPCFunc __imp____savevmx_24;
extern "C" PPCFunc __imp____savevmx_25;
extern "C" PPCFunc __imp____savevmx_26;
extern "C" PPCFunc __imp____savevmx_27;
extern "C" PPCFunc __imp____savevmx_28;
extern "C" PPCFunc __imp____savevmx_29;
extern "C" PPCFunc __imp____savevmx_30;
extern "C" PPCFunc __imp____savevmx_31;
extern "C" PPCFunc __imp____savevmx_64;
extern "C" PPCFunc __imp____savevmx_65;
extern "C" PPCFunc __imp____savevmx_66;
extern "C" PPCFunc __imp____savevmx_67;
extern "C" PPCFunc __imp____savevmx_68;
extern "C" PPCFunc __imp____savevmx_69;
extern "C" PPCFunc __imp____savevmx_70;
extern "C" PPCFunc __imp____savevmx_71;
extern "C" PPCFunc __imp____savevmx_72;
extern "C" PPCFunc __imp____savevmx_73;
extern "C" PPCFunc __imp____savevmx_74;
extern "C" PPCFunc __imp____savevmx_75;
extern "C" PPCFunc __imp____savevmx_76;
extern "C" PPCFunc __imp____savevmx_77;
extern "C" PPCFunc __imp____savevmx_78;
extern "C" PPCFunc __imp____savevmx_79;
extern "C" PPCFunc __imp____savevmx_80;
extern "C" PPCFunc __imp____savevmx_81;
extern "C" PPCFunc __imp____savevmx_82;
extern "C" PPCFunc __imp____savevmx_83;
extern "C" PPCFunc __imp____savevmx_84;
extern "C" PPCFunc __imp____savevmx_85;
extern "C" PPCFunc __imp____savevmx_86;
extern "C" PPCFunc __imp____savevmx_87;
extern "C" PPCFunc __imp____savevmx_88;
extern "C" PPCFunc __imp____savevmx_89;
extern "C" PPCFunc __imp____savevmx_90;
extern "C" PPCFunc __imp____savevmx_91;
extern "C" PPCFunc __imp____savevmx_92;
extern "C" PPCFunc __imp____savevmx_93;
extern "C" PPCFunc __imp____savevmx_94;
extern "C" PPCFunc __imp____savevmx_95;
extern "C" PPCFunc __imp____savevmx_96;
extern "C" PPCFunc __imp____savevmx_97;
extern "C" PPCFunc __imp____savevmx_98;
extern "C" PPCFunc __imp____savevmx_99;
extern PPCFunc __imp___snprintf;
extern PPCFunc __imp___snwprintf;
extern PPCFunc __imp___vscwprintf;
extern PPCFunc __imp___vsnprintf;
extern PPCFunc __imp___xstart;
extern PPCFunc __imp__sprintf;
extern PPCFunc __imp__swprintf;
extern PPCFunc __imp__vsprintf;
extern PPCFunc __imp__vswprintf;

const PPCFunc* g_importLinkTable[] = {
    &__imp__DbgBreakPoint,
    &__imp__DbgPrint,
    &__imp__ExAllocatePoolTypeWithTag,
    &__imp__ExCreateThread,
    &__imp__ExFreePool,
    &__imp__ExGetXConfigSetting,
    &__imp__ExRegisterTitleTerminateNotification,
    &__imp__ExTerminateThread,
    &__imp__FscSetCacheElementCount,
    &__imp__HalReturnToFirmware,
    &__imp__InterlockedFlushSList,
    &__imp__InterlockedPopEntrySList,
    &__imp__IoCheckShareAccess,
    &__imp__IoCompleteRequest,
    &__imp__IoCreateDevice,
    &__imp__IoDeleteDevice,
    &__imp__IoInvalidDeviceRequest,
    &__imp__IoRemoveShareAccess,
    &__imp__IoSetShareAccess,
    &__imp__KeAcquireSpinLockAtRaisedIrql,
    &__imp__KeBugCheck,
    &__imp__KeBugCheckEx,
    &__imp__KeDelayExecutionThread,
    &__imp__KeEnterCriticalRegion,
    &__imp__KeGetCurrentProcessType,
    &__imp__KeInitializeDpc,
    &__imp__KeInsertQueueDpc,
    &__imp__KeLeaveCriticalRegion,
    &__imp__KeLockL2,
    &__imp__KeQueryBasePriorityThread,
    &__imp__KeQueryPerformanceFrequency,
    &__imp__KeQuerySystemTime,
    &__imp__KeReleaseSpinLockFromRaisedIrql,
    &__imp__KeResetEvent,
    &__imp__KeSetAffinityThread,
    &__imp__KeSetBasePriorityThread,
    &__imp__KeSetCurrentProcessType,
    &__imp__KeSetEvent,
    &__imp__KeTlsAlloc,
    &__imp__KeTlsFree,
    &__imp__KeTlsGetValue,
    &__imp__KeTlsSetValue,
    &__imp__KeUnlockL2,
    &__imp__KeWaitForMultipleObjects,
    &__imp__KeWaitForSingleObject,
    &__imp__KfAcquireSpinLock,
    &__imp__KfReleaseSpinLock,
    &__imp__KiApcNormalRoutineNop,
    &__imp__MmAllocatePhysicalMemoryEx,
    &__imp__MmFreePhysicalMemory,
    &__imp__MmGetPhysicalAddress,
    &__imp__MmMapIoSpace,
    &__imp__MmQueryAddressProtect,
    &__imp__MmQueryAllocationSize,
    &__imp__NetDll_WSACleanup,
    &__imp__NetDll_WSAStartup,
    &__imp__NetDll_XNetGetTitleXnAddr,
    &__imp__NetDll_XNetStartup,
    &__imp__NetDll___WSAFDIsSet,
    &__imp__NetDll_accept,
    &__imp__NetDll_bind,
    &__imp__NetDll_closesocket,
    &__imp__NetDll_connect,
    &__imp__NetDll_inet_addr,
    &__imp__NetDll_listen,
    &__imp__NetDll_recv,
    &__imp__NetDll_select,
    &__imp__NetDll_send,
    &__imp__NetDll_setsockopt,
    &__imp__NetDll_socket,
    &__imp__NtAllocateVirtualMemory,
    &__imp__NtClearEvent,
    &__imp__NtClose,
    &__imp__NtCreateEvent,
    &__imp__NtCreateFile,
    &__imp__NtCreateSemaphore,
    &__imp__NtDuplicateObject,
    &__imp__NtFlushBuffersFile,
    &__imp__NtFreeVirtualMemory,
    &__imp__NtOpenFile,
    &__imp__NtQueryDirectoryFile,
    &__imp__NtQueryFullAttributesFile,
    &__imp__NtQueryInformationFile,
    &__imp__NtQueryVirtualMemory,
    &__imp__NtQueryVolumeInformationFile,
    &__imp__NtReadFile,
    &__imp__NtReadFileScatter,
    &__imp__NtReleaseSemaphore,
    &__imp__NtResumeThread,
    &__imp__NtSetEvent,
    &__imp__NtSetInformationFile,
    &__imp__NtSuspendThread,
    &__imp__NtWaitForSingleObjectEx,
    &__imp__NtWriteFile,
    &__imp__NtWriteFileGather,
    &__imp__ObCreateSymbolicLink,
    &__imp__ObDeleteSymbolicLink,
    &__imp__ObDereferenceObject,
    &__imp__ObIsTitleObject,
    &__imp__ObReferenceObject,
    &__imp__ObReferenceObjectByHandle,
    &__imp__RtlCaptureContext,
    &__imp__RtlCompareMemoryUlong,
    &__imp__RtlCompareStringN,
    &__imp__RtlEnterCriticalSection,
    &__imp__RtlFillMemoryUlong,
    &__imp__RtlFreeAnsiString,
    &__imp__RtlImageXexHeaderField,
    &__imp__RtlInitAnsiString,
    &__imp__RtlInitUnicodeString,
    &__imp__RtlInitializeCriticalSection,
    &__imp__RtlInitializeCriticalSectionAndSpinCount,
    &__imp__RtlLeaveCriticalSection,
    &__imp__RtlMultiByteToUnicodeN,
    &__imp__RtlNtStatusToDosError,
    &__imp__RtlRaiseException,
    &__imp__RtlTimeFieldsToTime,
    &__imp__RtlTimeToTimeFields,
    &__imp__RtlTryEnterCriticalSection,
    &__imp__RtlUnicodeStringToAnsiString,
    &__imp__RtlUnicodeToMultiByteN,
    &__imp__RtlUnwind,
    &__imp__RtlUpcaseUnicodeChar,
    &__imp__StfsControlDevice,
    &__imp__StfsCreateDevice,
    &__imp__VdCallGraphicsNotificationRoutines,
    &__imp__VdEnableDisableClockGating,
    &__imp__VdEnableRingBufferRPtrWriteBack,
    &__imp__VdGetCurrentDisplayGamma,
    &__imp__VdGetCurrentDisplayInformation,
    &__imp__VdGetSystemCommandBuffer,
    &__imp__VdInitializeEngines,
    &__imp__VdInitializeRingBuffer,
    &__imp__VdInitializeScalerCommandBuffer,
    &__imp__VdIsHSIOTrainingSucceeded,
    &__imp__VdPersistDisplay,
    &__imp__VdQueryVideoFlags,
    &__imp__VdQueryVideoMode,
    &__imp__VdRetrainEDRAM,
    &__imp__VdRetrainEDRAMWorker,
    &__imp__VdSetDisplayMode,
    &__imp__VdSetDisplayModeOverride,
    &__imp__VdSetGraphicsInterruptCallback,
    &__imp__VdSetSystemCommandBufferGpuIdentifierAddress,
    &__imp__VdShutdownEngines,
    &__imp__VdSwap,
    &__imp__XAudioGetSpeakerConfig,
    &__imp__XAudioGetVoiceCategoryVolume,
    &__imp__XAudioRegisterRenderDriverClient,
    &__imp__XAudioSubmitRenderDriverFrame,
    &__imp__XAudioUnregisterRenderDriverClient,
    &__imp__XGetAVPack,
    &__imp__XGetGameRegion,
    &__imp__XGetLanguage,
    &__imp__XGetVideoCapabilities,
    &__imp__XGetVideoMode,
    &__imp__XMACreateContext,
    &__imp__XMAReleaseContext,
    &__imp__XMsgCancelIORequest,
    &__imp__XMsgInProcessCall,
    &__imp__XMsgStartIORequest,
    &__imp__XMsgStartIORequestEx,
    &__imp__XNotifyGetNext,
    &__imp__XamAlloc,
    &__imp__XamContentClose,
    &__imp__XamContentCreateEnumerator,
    &__imp__XamContentCreateEx,
    &__imp__XamContentDelete,
    &__imp__XamContentGetCreator,
    &__imp__XamContentGetDeviceData,
    &__imp__XamContentGetDeviceState,
    &__imp__XamEnableInactivityProcessing,
    &__imp__XamEnumerate,
    &__imp__XamFree,
    &__imp__XamGetExecutionId,
    &__imp__XamGetSystemVersion,
    &__imp__XamInputGetCapabilities,
    &__imp__XamInputGetState,
    &__imp__XamInputSetState,
    &__imp__XamLoaderLaunchTitle,
    &__imp__XamLoaderTerminateTitle,
    &__imp__XamNotifyCreateListener,
    &__imp__XamParseGamerTileKey,
    &__imp__XamReadTileToTexture,
    &__imp__XamResetInactivity,
    &__imp__XamSessionCreateHandle,
    &__imp__XamSessionRefObjByHandle,
    &__imp__XamShowDeviceSelectorUI,
    &__imp__XamShowDirtyDiscErrorUI,
    &__imp__XamShowGamerCardUIForXUID,
    &__imp__XamShowMessageBoxUI,
    &__imp__XamShowMessageBoxUIEx,
    &__imp__XamShowSigninUI,
    &__imp__XamUserCheckPrivilege,
    &__imp__XamUserCreateStatsEnumerator,
    &__imp__XamUserGetName,
    &__imp__XamUserGetSigninInfo,
    &__imp__XamUserGetSigninState,
    &__imp__XamUserGetXUID,
    &__imp__XamUserReadProfileSettings,
    &__imp__XeCryptBnQwBeSigVerify,
    &__imp__XeCryptRotSumSha,
    &__imp__XeCryptSha,
    &__imp__XeKeysGetKey,
    &__imp__XexCheckExecutablePrivilege,
    &__imp__XexGetModuleHandle,
    &__imp__XexGetModuleSection,
    &__imp__XexGetProcedureAddress,
    &__imp__XexLoadImage,
    &__imp__XexUnloadImage,
    &__imp____C_specific_handler,
    &__imp____restfpr_14,
    &__imp____restfpr_15,
    &__imp____restfpr_16,
    &__imp____restfpr_17,
    &__imp____restfpr_18,
    &__imp____restfpr_19,
    &__imp____restfpr_20,
    &__imp____restfpr_21,
    &__imp____restfpr_22,
    &__imp____restfpr_23,
    &__imp____restfpr_24,
    &__imp____restfpr_25,
    &__imp____restfpr_26,
    &__imp____restfpr_27,
    &__imp____restfpr_28,
    &__imp____restfpr_29,
    &__imp____restfpr_30,
    &__imp____restfpr_31,
    &__imp____restgprlr_14,
    &__imp____restgprlr_15,
    &__imp____restgprlr_16,
    &__imp____restgprlr_17,
    &__imp____restgprlr_18,
    &__imp____restgprlr_19,
    &__imp____restgprlr_20,
    &__imp____restgprlr_21,
    &__imp____restgprlr_22,
    &__imp____restgprlr_23,
    &__imp____restgprlr_24,
    &__imp____restgprlr_25,
    &__imp____restgprlr_26,
    &__imp____restgprlr_27,
    &__imp____restgprlr_28,
    &__imp____restgprlr_29,
    &__imp____restgprlr_30,
    &__imp____restgprlr_31,
    &__imp____restvmx_100,
    &__imp____restvmx_101,
    &__imp____restvmx_102,
    &__imp____restvmx_103,
    &__imp____restvmx_104,
    &__imp____restvmx_105,
    &__imp____restvmx_106,
    &__imp____restvmx_107,
    &__imp____restvmx_108,
    &__imp____restvmx_109,
    &__imp____restvmx_110,
    &__imp____restvmx_111,
    &__imp____restvmx_112,
    &__imp____restvmx_113,
    &__imp____restvmx_114,
    &__imp____restvmx_115,
    &__imp____restvmx_116,
    &__imp____restvmx_117,
    &__imp____restvmx_118,
    &__imp____restvmx_119,
    &__imp____restvmx_120,
    &__imp____restvmx_121,
    &__imp____restvmx_122,
    &__imp____restvmx_123,
    &__imp____restvmx_124,
    &__imp____restvmx_125,
    &__imp____restvmx_126,
    &__imp____restvmx_127,
    &__imp____restvmx_14,
    &__imp____restvmx_15,
    &__imp____restvmx_16,
    &__imp____restvmx_17,
    &__imp____restvmx_18,
    &__imp____restvmx_19,
    &__imp____restvmx_20,
    &__imp____restvmx_21,
    &__imp____restvmx_22,
    &__imp____restvmx_23,
    &__imp____restvmx_24,
    &__imp____restvmx_25,
    &__imp____restvmx_26,
    &__imp____restvmx_27,
    &__imp____restvmx_28,
    &__imp____restvmx_29,
    &__imp____restvmx_30,
    &__imp____restvmx_31,
    &__imp____restvmx_64,
    &__imp____restvmx_65,
    &__imp____restvmx_66,
    &__imp____restvmx_67,
    &__imp____restvmx_68,
    &__imp____restvmx_69,
    &__imp____restvmx_70,
    &__imp____restvmx_71,
    &__imp____restvmx_72,
    &__imp____restvmx_73,
    &__imp____restvmx_74,
    &__imp____restvmx_75,
    &__imp____restvmx_76,
    &__imp____restvmx_77,
    &__imp____restvmx_78,
    &__imp____restvmx_79,
    &__imp____restvmx_80,
    &__imp____restvmx_81,
    &__imp____restvmx_82,
    &__imp____restvmx_83,
    &__imp____restvmx_84,
    &__imp____restvmx_85,
    &__imp____restvmx_86,
    &__imp____restvmx_87,
    &__imp____restvmx_88,
    &__imp____restvmx_89,
    &__imp____restvmx_90,
    &__imp____restvmx_91,
    &__imp____restvmx_92,
    &__imp____restvmx_93,
    &__imp____restvmx_94,
    &__imp____restvmx_95,
    &__imp____restvmx_96,
    &__imp____restvmx_97,
    &__imp____restvmx_98,
    &__imp____restvmx_99,
    &__imp____savefpr_14,
    &__imp____savefpr_15,
    &__imp____savefpr_16,
    &__imp____savefpr_17,
    &__imp____savefpr_18,
    &__imp____savefpr_19,
    &__imp____savefpr_20,
    &__imp____savefpr_21,
    &__imp____savefpr_22,
    &__imp____savefpr_23,
    &__imp____savefpr_24,
    &__imp____savefpr_25,
    &__imp____savefpr_26,
    &__imp____savefpr_27,
    &__imp____savefpr_28,
    &__imp____savefpr_29,
    &__imp____savefpr_30,
    &__imp____savefpr_31,
    &__imp____savegprlr_14,
    &__imp____savegprlr_15,
    &__imp____savegprlr_16,
    &__imp____savegprlr_17,
    &__imp____savegprlr_18,
    &__imp____savegprlr_19,
    &__imp____savegprlr_20,
    &__imp____savegprlr_21,
    &__imp____savegprlr_22,
    &__imp____savegprlr_23,
    &__imp____savegprlr_24,
    &__imp____savegprlr_25,
    &__imp____savegprlr_26,
    &__imp____savegprlr_27,
    &__imp____savegprlr_28,
    &__imp____savegprlr_29,
    &__imp____savegprlr_30,
    &__imp____savegprlr_31,
    &__imp____savevmx_100,
    &__imp____savevmx_101,
    &__imp____savevmx_102,
    &__imp____savevmx_103,
    &__imp____savevmx_104,
    &__imp____savevmx_105,
    &__imp____savevmx_106,
    &__imp____savevmx_107,
    &__imp____savevmx_108,
    &__imp____savevmx_109,
    &__imp____savevmx_110,
    &__imp____savevmx_111,
    &__imp____savevmx_112,
    &__imp____savevmx_113,
    &__imp____savevmx_114,
    &__imp____savevmx_115,
    &__imp____savevmx_116,
    &__imp____savevmx_117,
    &__imp____savevmx_118,
    &__imp____savevmx_119,
    &__imp____savevmx_120,
    &__imp____savevmx_121,
    &__imp____savevmx_122,
    &__imp____savevmx_123,
    &__imp____savevmx_124,
    &__imp____savevmx_125,
    &__imp____savevmx_126,
    &__imp____savevmx_127,
    &__imp____savevmx_14,
    &__imp____savevmx_15,
    &__imp____savevmx_16,
    &__imp____savevmx_17,
    &__imp____savevmx_18,
    &__imp____savevmx_19,
    &__imp____savevmx_20,
    &__imp____savevmx_21,
    &__imp____savevmx_22,
    &__imp____savevmx_23,
    &__imp____savevmx_24,
    &__imp____savevmx_25,
    &__imp____savevmx_26,
    &__imp____savevmx_27,
    &__imp____savevmx_28,
    &__imp____savevmx_29,
    &__imp____savevmx_30,
    &__imp____savevmx_31,
    &__imp____savevmx_64,
    &__imp____savevmx_65,
    &__imp____savevmx_66,
    &__imp____savevmx_67,
    &__imp____savevmx_68,
    &__imp____savevmx_69,
    &__imp____savevmx_70,
    &__imp____savevmx_71,
    &__imp____savevmx_72,
    &__imp____savevmx_73,
    &__imp____savevmx_74,
    &__imp____savevmx_75,
    &__imp____savevmx_76,
    &__imp____savevmx_77,
    &__imp____savevmx_78,
    &__imp____savevmx_79,
    &__imp____savevmx_80,
    &__imp____savevmx_81,
    &__imp____savevmx_82,
    &__imp____savevmx_83,
    &__imp____savevmx_84,
    &__imp____savevmx_85,
    &__imp____savevmx_86,
    &__imp____savevmx_87,
    &__imp____savevmx_88,
    &__imp____savevmx_89,
    &__imp____savevmx_90,
    &__imp____savevmx_91,
    &__imp____savevmx_92,
    &__imp____savevmx_93,
    &__imp____savevmx_94,
    &__imp____savevmx_95,
    &__imp____savevmx_96,
    &__imp____savevmx_97,
    &__imp____savevmx_98,
    &__imp____savevmx_99,
    &__imp___snprintf,
    &__imp___snwprintf,
    &__imp___vscwprintf,
    &__imp___vsnprintf,
    &__imp___xstart,
    &__imp__sprintf,
    &__imp__swprintf,
    &__imp__vsprintf,
    &__imp__vswprintf,
};

int main()
{
    // Actually read the table so section garbage collection cannot turn this
    // into a size-only test with no import relocations.
    for (const auto address : g_importLinkTable)
        if (!address) return 1;
    return int(sizeof(g_importLinkTable) / sizeof(g_importLinkTable[0]) != 456);
}
