#include <stdafx.h>
#include <shader/shader_cache.h>

#ifdef SONIC_GENERATIONS_HAVE_SHADER_CACHE
// Generated by tools/XenosRecomp once the shaders are recompiled.
extern const ShaderCacheEntry g_shaderCacheEntries[];
extern const size_t g_shaderCacheEntryCount;
#endif

bool ShaderCache::IsAvailable()
{
#ifdef SONIC_GENERATIONS_HAVE_SHADER_CACHE
    return g_shaderCacheEntryCount != 0;
#else
    return false;
#endif
}

size_t ShaderCache::GetSize()
{
#ifdef SONIC_GENERATIONS_HAVE_SHADER_CACHE
    return g_shaderCacheEntryCount;
#else
    return 0;
#endif
}

const ShaderCacheEntry* ShaderCache::Find(uint64_t hash)
{
#ifdef SONIC_GENERATIONS_HAVE_SHADER_CACHE
    for (size_t i = 0; i < g_shaderCacheEntryCount; i++)
    {
        if (g_shaderCacheEntries[i].hash == hash)
            return &g_shaderCacheEntries[i];
    }
#endif
    return nullptr;
}
