# Xenia's pinned FFmpeg fork provides XMAFRAMES, unlike upstream FFmpeg.
# Do not link system libavcodec alongside this fork: they export the same ABI.
set(XMA_FFMPEG_ROOT "${CMAKE_CURRENT_LIST_DIR}/../tools/ffmpeg-xma")
if (NOT EXISTS "${XMA_FFMPEG_ROOT}/libavcodec/wmaprodec.c")
    message(FATAL_ERROR "Run git submodule update --init tools/ffmpeg-xma")
endif()
if (NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$" OR APPLE)
    message(FATAL_ERROR "Pinned XMAFRAMES config currently supports Windows/Linux x86-64")
endif()
enable_language(C)
if (MSVC)
    # /RTC1 in CMake Debug defaults is incompatible with FFmpeg's required /O1.
    string(REPLACE "/RTC1" "" CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG}")
endif()
include(${CMAKE_CURRENT_LIST_DIR}/XmaFFmpegSources.cmake)
find_package(Threads REQUIRED)
add_library(xma_avutil STATIC ${XMA_AVUTIL_SOURCES})
add_library(xma_avcodec STATIC ${XMA_AVCODEC_SOURCES})
foreach(target xma_avutil xma_avcodec)
    target_include_directories(${target} PUBLIC ${XMA_FFMPEG_ROOT})
    target_compile_definitions(${target} PRIVATE HAVE_AV_CONFIG_H _USE_MATH_DEFINES)
    # FFmpeg relies on elimination of disabled feature branches, even in Debug.
    if (MSVC)
        target_compile_options(${target} PRIVATE /O1 /wd4996)
        target_compile_definitions(${target} PRIVATE _CRT_SECURE_NO_WARNINGS)
    else()
        target_compile_options(${target} PRIVATE -O2 -Wno-deprecated-declarations
            -include "${CMAKE_CURRENT_LIST_DIR}/xma_ffmpeg_config.h")
    endif()
    if (WIN32)
        target_include_directories(${target} PRIVATE ${XMA_FFMPEG_ROOT}/compat/atomics/win32)
    else()
        target_include_directories(${target} PRIVATE ${XMA_FFMPEG_ROOT}/compat/atomics/gcc)
    endif()
endforeach()
target_link_libraries(xma_avutil PUBLIC Threads::Threads)
if (WIN32)
    target_link_libraries(xma_avutil PUBLIC bcrypt)
else()
    target_link_libraries(xma_avutil PUBLIC m)
endif()
target_link_libraries(xma_avcodec PUBLIC xma_avutil)
add_library(SonicXmaFrames STATIC
    "${CMAKE_CURRENT_LIST_DIR}/../SonicGenerationsRecomp/apu/xma_frame_decoder.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/../SonicGenerationsRecomp/apu/xma_stream.cpp")
target_compile_features(SonicXmaFrames PUBLIC cxx_std_20)
target_include_directories(SonicXmaFrames PUBLIC "${CMAKE_CURRENT_LIST_DIR}/../SonicGenerationsRecomp")
target_link_libraries(SonicXmaFrames PRIVATE xma_avcodec)
